### ISSUE TITLE
Python error "Unable to find assembly 'Triton.BakeService'"

### ISSUE THREAD

**Issue by borogove** [microsoft/ProjectAcoustics#10]
UE 4.23 (custom), VS2019, Wwise 2019.1.5.

Managed to build my game with the changes noted in issue #7. 

The "Objects" and "Materials" tabs in the Acoustics menu seem to work; I can set acoustic properties for my scene's materials, but when I go to the "Probes" tab it says the Python plugin isn't available. Python plugin is installed and enabled, however. 

At launch, before going into the Acoustics menu, the UE output log shows the Triton.BakeService.dll getting loaded and unloaded with a bunch of surrounding exceptions and a Python stack trace:

```
'UE4Editor.exe' (Win32): Loaded 'C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Security\6a654c317ce4dba078abb5e13062ee95\System.Security.ni.dll'. 
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000067F78C5F50.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000067F78C5F50.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000067F78C5F50.
Exception thrown at 0x00007FF96CD5A839 (KernelBase.dll) in UE4Editor.exe: 0xE0434352 (parameters: 0xFFFFFFFF80070002, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FF91FB10000).
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000067F78C5F50.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000067F78C5F50.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000067F78C5F50.
Exception thrown at 0x00007FF96CD5A839 (KernelBase.dll) in UE4Editor.exe: 0xE0434352 (parameters: 0xFFFFFFFF80070002, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FF91FB10000).
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000067F78C5AC0.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000067F78C5AC0.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000067F78C5AC0.
Exception thrown at 0x00007FF96CD5A839 (KernelBase.dll) in UE4Editor.exe: 0xE0434352 (parameters: 0xFFFFFFFF80070002, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FF91FB10000).
'UE4Editor.exe' (Win32): Loaded 'D:\proj\phx\Dev-Main\Phoenix\Plugins\ProjectAcoustics\ThirdParty\Win64\Release\Triton.BakeService.dll'. 
'UE4Editor.exe' (Win32): Loaded 'D:\proj\phx\Dev-Main\Phoenix\Plugins\ProjectAcoustics\ThirdParty\Win64\Release\Triton.BakeService.dll'. 
'UE4Editor.exe' (Win32): Unloaded 'D:\proj\phx\Dev-Main\Phoenix\Plugins\ProjectAcoustics\ThirdParty\Win64\Release\Triton.BakeService.dll'
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: EEMessageException at memory location 0x00000067F78C6BF0.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: EEMessageException at memory location 0x00000067F78C6BF0.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: Exception at memory location 0x00000067F78C70B8.
Exception thrown at 0x00007FF96CD5A839 (KernelBase.dll) in UE4Editor.exe: 0xE0434352 (parameters: 0xFFFFFFFF80131515, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FF91FB10000).
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000067F78C5690.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000067F78C5690.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: Exception at memory location 0x00000067F78BF890.
Exception thrown at 0x00007FF96CD5A839 (KernelBase.dll) in UE4Editor.exe: 0xE0434352 (parameters: 0xFFFFFFFF80131515, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FF91FB10000).
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FF96CD5A839 in UE4Editor.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000067F78C5690.
Exception thrown at 0x00007FF96CD5A839 (KernelBase.dll) in UE4Editor.exe: 0xE0434352 (parameters: 0xFFFFFFFF80070002, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FF91FB10000).
Exception thrown at 0x00007FF96CD5A839 (KernelBase.dll) in UE4Editor.exe: 0xE0434352 (parameters: 0xFFFFFFFF80070002, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FF91FB10000).
Exception thrown at 0x00007FF96CD5A839 (KernelBase.dll) in UE4Editor.exe: 0xE0434352 (parameters: 0xFFFFFFFF80131604, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FF91FB10000).
'UE4Editor.exe' (Win32): Loaded 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\diasymreader.dll'. 
[2019.12.07-00.19.52:797][  1]LogPython: Error: Traceback (most recent call last):
[2019.12.07-00.19.52:797][  1]LogPython: Error:   File "D:/proj/phx/Dev-Main/Phoenix/Plugins/ProjectAcoustics/Content/Python/init_unreal.py", line 3, in <module>
[2019.12.07-00.19.52:797][  1]LogPython: Error:     import init_project_acoustics
[2019.12.07-00.19.52:797][  1]LogPython: Error:   File "D:/proj/phx/Dev-Main/Phoenix/Plugins/ProjectAcoustics/Content/Python\init_project_acoustics.py", line 39, in <module>
[2019.12.07-00.19.52:797][  1]LogPython: Error:     clr.AddReference("Triton.BakeService")
[2019.12.07-00.19.52:797][  1]LogPython: Error: FileNotFoundException: Unable to find assembly 'Triton.BakeService'.
[2019.12.07-00.19.52:797][  1]LogPython: Error:    at Python.Runtime.CLRModule.AddReference(String name)
[2019.12.07-00.19.52:864][  2]LogAssetRegistry: Asset discovery search completed in 5.9002 seconds
```

If I go to the Bake tab I hit an assertion breakpoint in `SAcousticsBakeTab::Refresh`; if I continue from there I crash in `FComputePoolConfigurationDetails::UpdateConfiguration`.

**Comment by MikeChemi** [comment]
It sounds like Triton.BakeService.dll was blocked from loading on your PC. To fix this, find Triton.BakeService.dll in File Explorer at <your_game>\Plugins\ProjectAcoustics\ThirdParty\Win64\Release. Right click on Triton.BakeService.dll and choose Properties. At the bottom of the properties window should be a checkbox that says "unblock." Click the unblock checkbox, hit OK, and then restart Unreal. The python error should be resolved.

**Comment by borogove** [comment]
All the DLLS and libs in that folder appear to have been "possibly blocked", yikes. Unblocking them got me past that and the probe and bake tabs are now appearing correctly. Thank you!
